# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - 'workflow-test'

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        architecture: x64

    - name: Build
      run: go build -v ./... -o buddy-prometheus-exporter-amd64

    - name: Test
      run: go test -v ./...

  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        architecture: arm64

    - name: Build
      run: go build -v ./... -o buddy-prometheus-exporter-arm64

    - name: Test
      run: go test -v ./...
